---

- name: Ansible Class
  hosts: all
  become: true
  become_method: sudo
  roles:
   - common

- name: "Configure the web servers"
  hosts: webserver
  become: true
  become_method: sudo
  roles:
   - webserver
