---

#Perform basic security setup

- name: "(Security) Disable firewall while we set up rules"
  ufw:
   state: disabled

- name: "(Security) Defaut firewall policy: deny incoming traffic"
  ufw:
   policy: deny
   direction: incoming

- name: "(Security) Defaut firewall policy: allow outgoing traffic"
  ufw:
   policy: allow
   direction: outgoing

- name: "(Security) Delete existing ssh rules"
  ufw:
   delete: yes
   rule: allow
   port: ssh

- name: "(Security) Allow incoming ssh connections, but limit the connetion rate of failures (6 per 30 seconds) and log this rule"
  ufw:
    rule: limit
    port: ssh
    proto: tcp
    log: yes

- name: "(Security) Enable firewall"
  ufw:
   state: enabled
